spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 9001
  tomcat:
    connection-timeout: 2s # set connection timeout
    keep-alive-timeout: 15s # how long your connection open until get new connection again
    threads:
      max: 50 # for local environment
      min-spare: 5

apps:
  greeting: "Welcome to the local book catalog"